version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automsg-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=automsg
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - WEBHOOK_URL=https://webhook.site/your-webhook-id
      - PORT=8080
      - MESSAGE_INITIAL_BATCH_SIZE=10
      - MESSAGE_PERIODIC_BATCH_SIZE=2
      - MESSAGE_INTERVAL_SECONDS=120
    depends_on:
      - postgres
      - redis
    networks:
      - automsg-network

  postgres:
    image: postgres:15-alpine
    container_name: automsg-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=automsg
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - automsg-network

  redis:
    image: redis:7-alpine
    container_name: automsg-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - automsg-network

networks:
  automsg-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 