// Code generated by MockGen. DO NOT EDIT.
// Source: automsg/pkg/persistence (interfaces: MessageRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/message_repository_mock.go -package=mocks automsg/pkg/persistence MessageRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "automsg/pkg/model/dto"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockMessageRepository) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockMessageRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockMessageRepository)(nil).BeginTx), ctx)
}

// GetSentMessages mocks base method.
func (m *MockMessageRepository) GetSentMessages(ctx context.Context, page, pageSize int) ([]dto.MessageDto, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentMessages", ctx, page, pageSize)
	ret0, _ := ret[0].([]dto.MessageDto)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSentMessages indicates an expected call of GetSentMessages.
func (mr *MockMessageRepositoryMockRecorder) GetSentMessages(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetSentMessages), ctx, page, pageSize)
}

// GetUnsentProcessingMessages mocks base method.
func (m *MockMessageRepository) GetUnsentProcessingMessages(ctx context.Context, limit int) ([]dto.MessageProcessingDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsentProcessingMessages", ctx, limit)
	ret0, _ := ret[0].([]dto.MessageProcessingDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsentProcessingMessages indicates an expected call of GetUnsentProcessingMessages.
func (mr *MockMessageRepositoryMockRecorder) GetUnsentProcessingMessages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsentProcessingMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetUnsentProcessingMessages), ctx, limit)
}

// LockMessageForProcessing mocks base method.
func (m *MockMessageRepository) LockMessageForProcessing(ctx context.Context, tx *sql.Tx, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockMessageForProcessing", ctx, tx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockMessageForProcessing indicates an expected call of LockMessageForProcessing.
func (mr *MockMessageRepositoryMockRecorder) LockMessageForProcessing(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockMessageForProcessing", reflect.TypeOf((*MockMessageRepository)(nil).LockMessageForProcessing), ctx, tx, id)
}

// MarkMessageAsSentTx mocks base method.
func (m *MockMessageRepository) MarkMessageAsSentTx(ctx context.Context, tx *sql.Tx, id int64, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessageAsSentTx", ctx, tx, id, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessageAsSentTx indicates an expected call of MarkMessageAsSentTx.
func (mr *MockMessageRepositoryMockRecorder) MarkMessageAsSentTx(ctx, tx, id, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessageAsSentTx", reflect.TypeOf((*MockMessageRepository)(nil).MarkMessageAsSentTx), ctx, tx, id, messageID)
}
