name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'

      - name: Run go mod tidy
        run: |
          set -e
          go mod tidy
          output=$(git status -s)
          if [ -z "${output}" ]; then
           exit 0
          fi
          exit 1

      - name: Build
        run: go build ./...